# All config variables accessible in 'site' object, e.g. site.timezone
timezone: Asia/Singapore

# SEO; see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Singapore Government Developer Portal
description: >
  Resources to help engineers and managers
  run and deliver great digital services,
  build on existing technologies and
  co-create innovative digital solutions with the Government
# url: "https://www.developer.gov.sg" # Disabling to have jekyll-redirect-from not obey site.url
logo: /assets/img/logo_developer.gov.sg.png

plugins:
  # SEO Usage:
  # Page front matter: title, description, image, author, lang
  - jekyll-seo-tag
  - jekyll-redirect-from

exclude:
  - functions
  - lambda
  - node_modules
  - scripts
  - apps/src
  - Dockerfile
  - Gemfile*
  - Gruntfile.js
  - netlify.toml
  - package*.json
  - webpack.config.js

collections_dir: collections

collections:
  technologies:
    output: yes
  guidelines:
    output: yes
  communities:
    output: yes
  singapore-government-tech-stack:
    output: yes

feedback_form: https://form.gov.sg/5e158a8b8967b800114d5a89
