# All config variables accessible in 'site' object, e.g. site.timezone
timezone: Asia/Singapore

# SEO; see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: developer.gov.sg
description: Resources for building Singapore Government digital products
url: "https://www.developer.gov.sg"
logo: /assets/img/logo_developer.gov.sg.png

plugins:
  - jekyll-assets
  - jekyll-seo-tag

include:
  - _redirects

exclude:
  - functions
  - lambda
  - node_modules
  - scripts
  - apps/src
  - Dockerfile
  - Gemfile*
  - Gruntfile.js
  - netlify.toml
  - package*.json
  - webpack.config.js

collections_dir: collections

collections:
  workflows:
    output: yes
  chapters:
    output: yes
  products:
    output: yes
  guidelines:
    output: yes
  events:
    output: yes
  general:
    output: yes
