# All config variables accessible in 'site' object, e.g. site.timezone
timezone: Asia/Singapore

# SEO; see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Singapore Government Developer Portal
description: >
  The Singapore Government Developer Portal is a one-stop resource hub for Government digital services and products.
# url: "https://www.developer.tech.gov.sg" # Need to disable this to have jekyll-redirect-from not obey site.url
logo: /assets/img/logo_developer.gov.sg.png
search_placeholder: Search

plugins:
  # SEO Usage:
  # Page front matter: title, description, image, author, lang
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-sitemap

exclude:
  - functions
  - lambda
  - node_modules
  - scripts
  - apps/src
  - Dockerfile
  - Gemfile*
  - Gruntfile.js
  - netlify.toml
  - package*.json
  - webpack.config.js

collections_dir: collections

collections:
  products:
    output: yes
  guidelines:
    output: yes
  communities:
    output: yes
  singapore-government-tech-stack:
    output: yes

feedback_form: https://form.gov.sg/60f7b3df8c8a4a00115c2e49
feedback_form_url_field: 60efdac78c8a4a0011f25c69
domain: https://developer.tech.gov.sg
